# Generated by Django 3.2.3 on 2021-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accidentID', models.CharField(max_length=200)),
                ('yearMonth', models.CharField(max_length=200)),
                ('processingUnit', models.CharField(max_length=200)),
                ('accidentLevel', models.CharField(max_length=200)),
                ('accidentTime', models.CharField(max_length=200)),
                ('dist', models.CharField(max_length=200)),
                ('streetRoad', models.CharField(max_length=200)),
                ('roadclass', models.CharField(max_length=200)),
                ('roadType', models.CharField(max_length=200)),
                ('light', models.CharField(max_length=200)),
                ('accidentType', models.CharField(max_length=200)),
                ('whether', models.CharField(max_length=200)),
                ('deathNum', models.CharField(max_length=200)),
                ('injuryNum', models.CharField(max_length=200)),
                ('roadStatus', models.CharField(max_length=200)),
                ('roadDefect', models.CharField(max_length=200)),
                ('speedLimit', models.CharField(max_length=200)),
                ('obstacle', models.CharField(max_length=200)),
                ('positionX', models.CharField(max_length=200)),
                ('positionY', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-accidentTime',),
            },
        ),
    ]
