# Generated by Django 3.2.3 on 2021-06-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedMeasuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraID', models.CharField(max_length=20)),
                ('cameraType', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=20)),
                ('limit', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('ViolationType', models.CharField(max_length=20)),
                ('positionX', models.CharField(max_length=20)),
                ('positionY', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('-cameraID',),
            },
        ),
    ]
