# Generated by Django 3.2.3 on 2021-06-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_speedmeasuring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficaccident',
            old_name='whether',
            new_name='weather',
        ),
    ]
